epic:
  app_id: '8ba7dd62-013b-4c3f-94b2-2f10004a8dde'
  redirect_uri: 'https://fhir-patient-portal.herokuapp.com/oauth/epic/callback'
  #redirect_uri: 'http://127.0.0.1:5000/oauth/epic/callback'
  api_base: 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/STU3/'

smart:
    app_id: '8ba7dd62-013b-4c3f-94b2-2f10004a8dde'
    redirect_uri: 'https://fhir-patient-portal.herokuapp.com/oauth/smart/callback'
    #redirect_uri: 'http://127.0.0.1:5000/oauth/smart/callback'
    api_base: 'https://launch.smarthealthit.org/v/r3/sim/eyJrIjoiMSIsImIiOiJlNjZhMmFmOS02ZTY2LTQ5OTItOTdhMS1hMTZlNmZkNmQ2NDIifQ/fhir'

logica:
    app_id: '8ba7dd62-013b-4c3f-94b2-2f10004a8dde'
    redirect_uri: 'http://fhir-patient-portal.herokuapp.com/oauth/logica/callback'
    redirect_uri_local: 'http://127.0.0.1:5000/oauth/logica/callback'
    api_base: 'https://api.logicahealth.org/patientportal/data/'
