epic:
  app_id: 'your-app-id' #register to epic app orchard to get your app id
  redirect_uri: 'http://127.0.0.1:5000/oauth/epic/callback'
  api_base: 'https://fhir.epic.com/interconnect-fhir-oauth/api/FHIR/STU3/'

smart:
    app_id: 'testing-app-id'
    redirect_uri: 'http://127.0.0.1:5000/oauth/smart/callback'
    api_base: 'https://launch.smarthealthit.org/v/r3/sim/eyJrIjoiMSIsImIiOiJlNjZhMmFmOS02ZTY2LTQ5OTItOTdhMS1hMTZlNmZkNmQ2NDIifQ/fhir'
