"""correct identifier_system typo

Revision ID: 8b43a2853033
Revises: cef135d1d582
Create Date: 2021-01-04 23:54:37.533036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b43a2853033'
down_revision = 'cef135d1d582'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('identifier_sysyem')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('identifier_sysyem', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
