"""correct identifier_system typo

Revision ID: a469060ab2e5
Revises: e2b654158c4a
Create Date: 2021-01-04 23:45:19.225979

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a469060ab2e5'
down_revision = 'e2b654158c4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identifier_sysyem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier_sysyem', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
