"""change table name to users

Revision ID: cef135d1d582
Revises: f7bfb099d5c7
Create Date: 2021-01-04 23:49:04.131192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef135d1d582'
down_revision = 'f7bfb099d5c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'identifier_sysyem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier_sysyem', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
