"""correct identifier_system typo

Revision ID: e2b654158c4a
Revises: b018ff7aa42a
Create Date: 2021-01-04 23:43:59.675447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2b654158c4a'
down_revision = 'b018ff7aa42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier_system', sa.String(), nullable=True))
    op.drop_column('users', 'identifier_sysyem')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('identifier_sysyem', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'identifier_system')
    # ### end Alembic commands ###
